# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  笑对生活
subtitle: 分享技术，品味人生
name: 笑对生活 
email: 18753370912@163.com
description: 本站是笑对生活的技术分享博客。内容涵盖网络、嵌入式知识分享。
keywords: 网络,嵌入式,c++,c,Python,
encoding: "utf-8"
favicon: favicon.ico 

repository: zhaorong2020/zhaorong2020.github.io
github_url: http://github.com/zhaorong2020
url: http://zhaorong2020.github.io
enforce_ssl: zhaorong2020.com

## Gem
plugins_dir:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:


  -
    href: /spring-cloud.html
    label: SCloud
    target: _self

  -
    href: /it.html
    label: 深度
    target: _self

  -
    href: /money.html
    label: 小知识
    target: _self   

  -
    href: /life.html
    label: 故事
    target: _self

  -
    href: /arch.html
    label: 架构
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self

  -
    href: /about.html
    label: 关于
    target: _self

# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /linux.html
    label: Linux
    target: _self

  -
    href: /network-protocol.html
    label: Network
    target: _self
    subnav:

      -
        subHref: /network-protocol.html
        subLabel: network-protocol

      -
        subHref: /network-socket.html
        subLabel: network-socket

  -
    href: http://www.justdojava.com
    label: 算法
    target: _blank
    subnav:

      -
        subHref: /java.html
        subLabel: 数据结构
        
      -
        subHref: http://www.justdojava.com
        subLabel: 算法
        target: _blank

  -
    
    href: /python.html
    label: Python
    subnav:

      -
        subHref: /python.html
        subLabel: Python 教程
        
      -
        subHref: http://www.justdopython.com
        subLabel: Python 技术
        target: _blank

  -
    href: /archives.html
    label: Archives
    target: _self



# labels. my blog key words
labels:

  -
    href: /payment.html
    label: Pay     
    target: _self

  -
    href: /fastdfs.html
    label: FastDFS
    target: _blank

  -
    href: /mongodb.html
    label: MongoDB
    target: _blank

  -
    href: /docker.html
    label: Docker
    target: _blank

  -
    href: /open-source.html
    label: Code  
    target: _blank

  -
    href: /gitchat.html
    label: Chat
    target: _blank


# selected articles
classes:

  -
    href: /cartoon.html
    name: 不会笑青年
    describe: 内心沉稳 ，放荡不羁。

  -
    href: /life.html
    name: 我的故事
    describe: 生活就是故事，故事就是生活

  -
    href: /it.html
    name: IT行业深度报道
    describe: IT大佬，互联网知名公司的故事




# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]
gems: [jekyll-paginate]

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: zhaorong2020
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zhaorong2020
    repo: blogtalk
    oauth:
        client_id: 675cc7e85c4d576adb67
        client_secret: 4c0c5c37ea4fbfcedd1be8538d13c30393198d20
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zhaorong2020
    repo: blogtalk
    clientID: 675cc7e85c4d576adb67
    clientSecret: 4c0c5c37ea4fbfcedd1be8538d13c30393198d20
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
